"""phase5_rbac_and_settings

Revision ID: 84c9ae04acfd
Revises: b0c7f0757f41
Create Date: 2026-07-01 16:02:28.387022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c9ae04acfd'
down_revision: Union[str, None] = 'b0c7f0757f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_articles')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_articles_last_modified_by_id_users'), 'users', ['last_modified_by_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_publish', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.drop_column('can_publish')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_articles_last_modified_by_id_users'), type_='foreignkey')

    op.create_table('_alembic_tmp_articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content_html', sa.TEXT(), nullable=False),
    sa.Column('meta_description', sa.VARCHAR(length=160), nullable=False),
    sa.Column('focus_keyword', sa.VARCHAR(), nullable=False),
    sa.Column('seo_score', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('wp_post_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('last_modified_by_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by_id'], ['users.id'], name='fk_articles_last_modified_by_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
